---
- name: Install necessary softwares
  hosts: maquinas
  strategy: free
  become: true
  tasks:
    - name: Update the software package dependecy.
      ansible.builtin.shell:
        "apt install fail2ban "
