---
- name: Update web servers
  hosts: all
  become: true
  become_method: sudo
  become_user: semaphore

  tasks:
  - name: Check system information
    shell: "sudo touch /teste"
    register: os_info
  - debug:
      msg: "{{os_info.stdout_lines}}"
  - name: Creating an empty file
    file:
      path: "/teste"
      state: touch
    become: true
    become_method: sudo
    become_user: semaphore
  - name: Install apache httpd 
    ansible.builtin.apt:
      name: fail2ban
      state: present
    become: true
    become_method: sudo
    become_user: semaphore
