---
- name: Update web servers
  hosts: all
  become: true
  become_method: enable

  tasks:
  - name: Install apache httpd 
    ansible.builtin.apt:
      name: fail2ban
      state: present
    become: true
    become_method: enable
